volumes:
  gmodserver:
  csgoserver:

services:
    linuxgsm-gmod:
        build:
          context: .
          args:
            LGSM_GAMESERVER: gmodserver
        volumes:
          - gmodserver:/home/linuxgsm
          - /etc/localtime:/etc/localtime:ro
        restart: always
        tty: true
    linuxgsm-csgo:
        build:
          context: .
          args:
            LGSM_GAMESERVER: csgoserver
        volumes:
          - csgoserver:/home/linuxgsm
          - /etc/localtime:/etc/localtime:ro
        restart: always
        tty: true
        ports:
          - "27015:27015"
